
#ifndef __QHYCCDDATA_H__
#define __QHYCCDDATA_H__


#if LIBUSB_MODE_SUPPORT
#if (defined (__APPLE__)&&defined( __MACH__)) ||(defined(__linux__ )&&defined (__ANDROID__))


#include "firmware/IC16200A_HEX.h"
#include "firmware/QHY09000A_HEX.h"
#include "firmware/POLEMASTER_HEX.h"
#include "firmware/QHY16200A_HEX.h"
#include "firmware/QHY20_HEX.h"
#include "firmware/QHY290_img.h"
#include "firmware/QHY5III185_img.h"
#include "firmware/QHY7_HEX.h"
#include "firmware/miniCam5_HEX.h"
#include "firmware/QHY16803A_HEX.h"
#include "firmware/QHY10_HEX.h"
#include "firmware/QHY163_img.h"
#include "firmware/QHY21_HEX.h"
#include "firmware/QHY29_HEX.h"
#include "firmware/QHY5III224_img.h"
#include "firmware/QHY814A_HEX.h"
#include "firmware/IC8300_HEX.h"
#include "firmware/QHY11_HEX.h"
#include "firmware/QHY165_img.h"
#include "firmware/QHY224_img.h"
#include "firmware/QHY2E_HEX.h"
#include "firmware/QHY5III290_img.h"
#include "firmware/QHY8L_HEX.h"
#include "firmware/IC90A_HEX.h"
#include "firmware/QHY128_img.h"
#include "firmware/QHY168_img.h"
#include "firmware/QHY22_HEX.h"
#include "firmware/QHY2PRO_HEX.h"
#include "firmware/QHY5II_HEX.h"
#include "firmware/QHY8M_HEX.h"
#include "firmware/IMG0H_HEX.h"
#include "firmware/QHY12_HEX.h"
#include "firmware/QHY16_HEX.h"
#include "firmware/QHY23_HEX.h"
#include "firmware/QHY2_HEX.h"
#include "firmware/QHY5LOADER_HEX.h"
#include "firmware/QHY8PRO_HEX.h"
#include "firmware/IMG2P_HEX.h"
#include "firmware/QHY15_HEX.h"
#include "firmware/QHY174_img.h"
#include "firmware/QHY247_img.h"
#include "firmware/QHY367_img.h"
#include "firmware/QHY5_HEX.h"
#include "firmware/QHY8_HEX.h"
#include "firmware/IMG2S_HEX.h"
#include "firmware/QHY160002AD_HEX.h"
#include "firmware/QHY178_img.h"
#include "firmware/QHY27_HEX.h"
#include "firmware/QHY5III174_img.h"
#include "firmware/QHY695A_HEX.h"
#include "firmware/QHY90A_HEX.h"
#include "firmware/IMG50_HEX.h"
#include "firmware/QHY16000_HEX.h"
#include "firmware/QHY183_img.h"
#include "firmware/QHY28_HEX.h"
#include "firmware/QHY5III178_img.h"
#include "firmware/QHY6_HEX.h"
#include "firmware/QHY9S_HEX.h"
#include "firmware/QHY42_img.h"
#include "firmware/QHY42PRO_img.h"
#include "firmware/QHY294_img.h"
#include "firmware/QHY294PRO_img.h"
#include "firmware/QHY550_img.h"
#include "firmware/QHY2020_img.h"
#include "firmware/QHY4040_img.h"
#include "firmware/QHY6060_img.h"
#include "firmware/QHY411ERIS_img.h"
#include "firmware/QHY0204_img.h"
#include "firmware/QHY600_img.h"
#include "firmware/QHY411_img.h"
#include "firmware/QHY247_img.h"
#include "firmware/QHY367PRO_img.h"
#include "firmware/QHY268_img.h"
#include "firmware/QHY4040PRO_img.h"
#include "firmware/QHY128PRO_img.h"
#include "firmware/QHY5III462_img.h"
#include "firmware/QHY410_img.h"
#include "firmware/QHY533_img.h"
#include "firmware/QHY461_img.h"
#include "firmware/QHY5III485_img.h"
#include "firmware/QHY432_img.h"
#include "firmware/QHY5III482_img.h"
#include "firmware/QHY5III334_img.h"
#include "firmware/QHY342_img.h"
#include "firmware/QHY990_img.h"
#include "firmware/QHY183A_img.h"
#include "firmware/QHY991_img.h"

#endif
#endif



#endif

