cd .
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_1_SearchCamera.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_2_GetReadMode.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_2_SetReadMode.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_3_SetStreamMode.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_4_InitCamera.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_5_SetFormat.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_5_SetBIN.cpp
% 
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetCoolerOFF.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetCoolerPWM.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetCoolerTemperature.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetDDR.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetExposeTime.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetGain.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetLiveBrightness.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetLiveContrast.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetLiveGamma.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetLiveWBB.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetLiveWBG.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetLiveWBR.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetOffset.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetROI.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_6_SetTraffic.cpp
% 
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_7_GetChipInfo.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_7_GetDebayer.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_7_GetEffective.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_7_GetHumidity.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_7_GetOverscan.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_7_GetPressure.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_7_GetTemperature.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_8_CheckCFWPlug.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_8_GetCFWSlotsNum.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_8_GetCFWStatus.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_8_SetCFWTarget.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_9_BeginSingleExpose.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_9_GetOneSingleFrame.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_9_StopSingleCapture.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_10_BeginLiveExpose.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_10_GetOneLiveFrame.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_10_StopLiveCapture.cpp
mex -Llib\x64\vc12 -lqhyccd -outdir output\x64  -Iinclude -ULINUX -DWIN32 src\QHY_11_CloseCamera.cpp